server:
  port: 0

spring:
  datasource:
    username: *
    password: *
    url: jdbc:mysql://*/shark-link?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5
  data:
    redis:
      host: *
      port: 0
      password: *
      database: 7
  mvc:
    view:
      prefix: /templates/
      suffix: .html

short-link:
  domain:
    default: *