server:
  port: 0

spring:
  datasource:
    username: 0
    password: 0
    url: jdbc:mysql://*/shark-link?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5
  data:
    redis:
      host: 0
      port: 0
      password: *
      database: 7

short-link:
  remote:
    createUrl:
      default: *
    pageUrl:
      default: *
    updateUrl:
      default: *
    getTitleUrl:
      default: *
    recycleSaveUrl:
      default: *
    recyclePageUrl:
      default: *
    recycleRecoverUrl:
      default: *

