server:
  port: 8002

spring:
  datasource:

    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: *
      port: 0
      password: *
      database: 7

short-link:
  remote:
    createUrl:
      default: http://127.0.0.1:8001/api/short-link/v1/create
    pageUrl:
      default: http://127.0.0.1:8001/api/short-link/v1/page
    updateUrl:
      default: http://127.0.0.1:8001/api/short-link/v1/update
    getTitleUrl:
      default: http://127.0.0.1:8001/short-link/v1/title?url=
    recycleSaveUrl:
      default: http://127.0.0.1:8001/api/short-link/v1/recycle-bin/save
    recyclePageUrl:
      default: http://127.0.0.1:8001/api/short-link/v1/recycle-bin/page
    recycleRecoverUrl:
      default: http://127.0.0.1:8001/api/short-link/v1/recycle-bin/recover
